In [33]:
#Regularization is a way to reduce model overfitting and variance
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv("Advertising.csv")

In [35]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [36]:
X = df.drop('sales', axis=1)
y = df['sales']

In [37]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [38]:
poly_features = polynomial_converter.fit_transform(X)
X.shape

(200, 3)

In [39]:
poly_features.shape

(200, 19)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [41]:
X_train.shape

(140, 19)

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [43]:
X_train = scaler.transform(X_train)
X_test =scaler.transform(X_test)

In [44]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [45]:
#poly_features[0]

Ridge Regression

In [46]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [47]:
test_prediction = ridge_model.predict(X_test)

In [48]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, test_prediction)
MAE

0.5774404204714167

In [49]:
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))
RMSE

0.894638646131965

In [50]:
from sklearn.linear_model import RidgeCV
ridge_cv_model = RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error')
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [51]:
ridge_cv_model.alpha_

0.1

In [52]:
# from sklearn.metrics import SCORERS
# SCORERS.keys()

In [53]:
test_prediction = ridge_cv_model.predict(X_test)
MAE = mean_absolute_error(y_test, test_prediction)
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))

In [54]:
MAE

0.4273774884351013

In [55]:
RMSE

0.6180719926948981

In [56]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [57]:
ridge_cv_model.best_score_

-0.3749223340292953

Lasso Regression - least absolute shrinkage and selection operator

In [61]:
from sklearn.linear_model import LassoCV
# lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1000000)
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [62]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [63]:
lasso_cv_model.alpha_

0.4943070909225832

In [64]:
test_prediction = lasso_cv_model.predict(X_test)
MAE = mean_absolute_error(y_test, test_prediction)
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))

In [65]:
MAE

0.6541723161252867

In [66]:
RMSE

1.1308001022762548

In [67]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

L1 and L2 Regularization - Elastic Net

In [72]:
from sklearn.linear_model import ElasticNetCV
elastic_model = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [73]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [75]:
elastic_model.l1_ratio_

1.0

In [76]:
elastic_model.alpha_

0.004943070909225833

In [77]:
lasso_cv_model.alpha_

0.4943070909225832

In [78]:
elastic_model.predict(X_test)
MAE = mean_absolute_error(y_test, test_prediction)
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))

In [79]:
MAE

0.6541723161252867

In [80]:
RMSE

1.1308001022762548